### ISSUE TITLE
Load Addon button not dissapearing

### ISSUE THREAD

**Issue by s1lv3rw0lf** [Excrulon/Tree-of-Savior-Lua-Mods#116]
Hello, i decided to try this mod today, and after installing and running the game. I get the Load Addon button, once clicked i get 3 mods loading messages, but the button doesnt dissapear. Could be the addons arent loading properly?

System: Win 7 - 64 bits

**Comment by s1lv3rw0lf** [comment]
After checking around, i found it was windows native unzipper changing a filename. It works fine using 7zip to uncompress. Sorry for the trouble

**Comment by Excrulon** [comment]
# If your load addon button gets stuck on the screen, your zip program probably removed or corrupted the unicode character in the ipf filename. Make sure the experience card calculator ipf is named this after extracting:

#### ☃expcardcalculator.ipf

This is just due to the patcher not checking for unicode characters in filenames when it deletes every other file not on their list. Hopefully I can find another way to load stuff so we don't even need to deal with this workaround anymore. May just go back to packing stuff in SumAni.ipf or something.
