### ISSUE TITLE
Item name Colors

### ISSUE THREAD

**Issue by pedrobj** [Excrulon/Tree-of-Savior-Lua-Mods#24]
Basically put their quality color in the name.
- Tooltip
- Inventory
- Chat
- Market

It's possible through addon?

**Comment by TehSeph** [comment]
I was actually looking into having a go at this myself, along with always showing item names on the ground instead of having to hold alt and stopping character movement. I'm sure Excrulon could do it better (since I have very little knowledge on both lua and ToS) but if I finish it first I'll make sure to share and possibly make a pull request. :smiley:

**Comment by TehSeph** [comment]
Check: https://github.com/TehSeph/tos-addons
This issue can be closed. :smiley:
