### ISSUE TITLE
Recall pet to default position if pet is lost from screen

### ISSUE THREAD

**Issue by tetsjn** [Excrulon/Tree-of-Savior-Lua-Mods#30]
Hi Excrulon,

First off, I want to say thank you for taking the initiative to code the add-ons. I've created a profile just to star your add-on and might consider to contribute if this goes further. In summary, I am a big fan of your work. :)

I have a request and I am not sure if this can be done. Is there a way that we can recall our pet to a default location besides switching the pet on and off because that trick doesn't seem to work all the time and I am stuck not mounted on my pet as I am a cataphract and I highly depend on my mount in battle. Just a little opinion representing all the cataphracts out there.

Thank you again!

Cheers.

B.R.,
tetsjN

**Comment by rafaelfillipesilva** [comment]
Hi Excrulon,

I've sent you a pm in forums with something I thought about this issue as I have the same one. IMC just ignores it since iCBT.

I said 4 ideas I had that helps us at least to log/track the issue and try to find a workaround in the game itself.

I think the main reasons about this are:
1. Pet position sync problems. But if you get near the pet after the bug the character will be mounted but without the Riding status.
2. Client-side VehicleStatus problem. That in theory could be forced to "false" to allow the player to ride the pet again.
3. Both. So being able to force VehicleStatus to false we could do like, disable the pet, force VehicleStatus, enable the pet, try to Ride it.
4. We know where we died/sit when the bug happened so we can go back there. Assuming that you can enable that log line I said in the pm we could do a proper testing if forcing VehicleStatus to false while trying to mount the pet near the real position of it could be helpful.

Thanks in advance!

**Comment by Excrulon** [comment]
I'm not really interested in working on any pet addons right now, I have
too many other priorities. Someone else can though. And you do have free
time as you're over level 200, you just don't want to spend it doing work.
;)

**Comment by rafaelfillipesilva** [comment]
Welp, actually over 270. I can try but alone I'll take days and my vacations ends on next Monday. Still I'm having some issue with stress 'cause of last months in uni so not enough brain power to think a lot (mindlessy questing/grinding is possible) :<

Then is it possible for you to say how can I access the variables in the game's scope? Like control, GetMyActor and so. Didn't find any reference on how to do this in your scripts. Only the "world" which calls GetActor or "info" which aren't referenced in any place that I looked. So I can try to do it and help everybody with the same problem? ;)

**Comment by Excrulon** [comment]
Hah that makes it even worse. I'm only like 103, sheesh.

You just call those functions as you want. They should all be in global
scope.

If someone lets me use their account that has a mounted class on it, I'll
look into it after I finish up all my other priorities.

**Comment by rafaelfillipesilva** [comment]
Hmm. What causes the game to crash/get stuck 'cause of addons? I tried following your pattern to add a hook that used SysMsg to say "onoff=0" / "onoff=1". Code was ok. So global references are ok too. I'll try again. Is there something that I should take care while trying to add this logging things to your addon?

**Comment by Excrulon** [comment]
I don't know, you'll have to show me your code.

**Comment by rafaelfillipesilva** [comment]
Got it. Managed to track it a bit. Do you know if there's a public way to change the internal values of "GetVehicleState" or to know the variable name? (Or by chance have an reference of this table?)

**Comment by rafaelfillipesilva** [comment]
So, I really need some help.

The game checks everywhere for GetVehicleState and it is set to true even when our pet are glitched (mounted but can't use skill nor have the buff Riding).

I'm currently trying to find a way to make the game know it shouldn't be mounted. By chance could you have any ideia? :<

**Comment by Excrulon** [comment]
I don't know, it's just a lot of trial and error. Sounds like the bug could
be on the server and then there's nothing we can do about it. Also not even
sure that variable represents whether you're mounted or not. Positive it is?

**Comment by rafaelfillipesilva** [comment]
It is checked to enable skills on the skill bar and to prevent you from disabling the pet while mounted.

Like: the bug happened and GetVehicleState returns true. You are visually riding the pet. Theoretically, could use like Retreat Shot skill but then nothing happens. If you go away from the region your pet is (like if going out of the screen the place it was last seen) you'll visually dismount it and GetVehicleState will return false.

In the region it is if you try to dismount it you can do everything, even calling RideCompanion directly. It won't work and you'll still be mounted. If you're out of that place you can't use skills nor it'll follow you.

Also, disabling and re-enabling the pet will recall it to your position and the bug will still exist.

It only happens when:
1) You die and somehow the game forces you to ride the pet when you spawn and it bugs.
2) You sit down and then magically the pet disappears, when you go near where it should be you'll ride it only visually and the bug is applied.

I guess it's something like... the server treats it correctly (like, not letting you use the skills nor dismount because you are already dismounted) and the client still have information that you are mounted and do sanity-checks to prevent like riding the pet twice. I'm also assuming that we get buff updates from the server and that's why the Riding status is not shown.

But I don't have any information of what's behind Actors and these states nor how it applies pet status in animations.

petthing.lua:
```
local petHook = "ON_RIDING_VEHICLE";
local petOld = "ON_RIDING_VEHICLE_OLD";

local pet2Hook = "TOGGLE_PET_ACTIVITY";
local pet2Old = "TOGGLE_PET_ACTIVITY_OLD";

function ON_RIDING_VEHICLE_HOOKED(onoff)
	if onoff == 0 then	
		ui.SysMsg("Tried to dismount!");
	else
		ui.SysMsg("Tried to ride!");
	end
	
	_G[petOld](onoff);
end

function TOGGLE_PET_ACTIVITY_HOOKED(parent, ctrl)
	control.RideCompanion(0);
	_G[pet2Old](parent, ctrl);
	control.RideCompanion(0);
end

if _G[petOld] == nil then
	_G[petOld] = _G[petHook];
	_G[petHook] = ON_RIDING_VEHICLE_HOOKED;
else
	_G[petHook] = ON_RIDING_VEHICLE_HOOKED;
end

if _G[pet2Old] == nil then
	_G[pet2Old] = _G[pet2Hook];
	_G[pet2Hook] = TOGGLE_PET_ACTIVITY_HOOKED;
else
	_G[pet2Hook] = TOGGLE_PET_ACTIVITY_HOOKED;
end

ui.SysMsg("Pet thing loaded!");
```

**Comment by Excrulon** [comment]
I guess I'll look through a little code when I get home. Sounds like you'd
need to figure out how to send the mount/dismount request to the server
properly. Can't say for sure yet. And I have no mounted class to test stuff
with so I can't really do anything.

**Comment by rafaelfillipesilva** [comment]
Sorry for asking too much but I would appreciate if you could help a bit too. To be honest most of the game is possible to do without this fix. We can just leave the dungeon or change channels - annoying but ok.

But there's a new problem. As a Reiter (or Cata) in Earth Tower you can't die - 0 deaths runs for you otherwise it's a lottery, if it bugs you are done. There's no time to come back and you don't have enough DPS to help the party :<

I'll look a bit more. Do you know how to access the info of that RideCompanion and other functions? I couldn't find where they are so I'm assuming they're out of lua scope D:

**Comment by Excrulon** [comment]
Haha I have been helping. I can't help much further unless I have an account with a character that uses a mount.

You'll just have to dump the table to a file, usually what I do. Can dump everything on _G as well.

**Comment by rafaelfillipesilva** [comment]
I dumped the result of GetMyActor and its metatable. There's only GetVehicleActor and GetVehicleActorHandleVal new and GetVehicleActor either returned null or an empty table or couldn't be dumped nor its metatable (I didn't gave it much attention as it might not have anything useful).

But I should've dumped "control", I think. I'll try that later (after uni ;-;). If I get some free time I'll make a new steam account and level a Cata to ~130, worth it anyway but should takes days since I need to focus in trying to get better gears and so for ET ;-;

And yes, thanks for the help \o
