### ISSUE TITLE
Can you integrate this

### ISSUE THREAD

**Issue by Fornori** [Excrulon/Tree-of-Savior-Lua-Mods#50]
http://www.pro-tos.ru/community/resources/cwlibrary.8/

This addon show how many Gold you farm in the session and per mobe

**Comment by fiote** [comment]
Hey Fornori! That's my addon, lol. Why would you want it to be 'integrated'? That's a separated thing, you can install it too.

**Comment by zckrs** [comment]
@fiote I think user/player would like one central place to get/use addons.

**Comment by Excrulon** [comment]
Not my addon to integrate. Was working on some centralized way everyone
could do addons but I stopped caring because everyone has different
styles/preferences so everyone will never agree on things. I'm just gonna
keep doing my thing.

**Comment by Fornori** [comment]
Yep. I dont' want to gitt pull from many places. I want One center store for addons $)
Maybe somebody create the installer for addons? 
I want I cant do this - simple application on c# or Java :)

**Comment by Fornori** [comment]
It you start do this. For this reason we can develop one format for support installer. IF other want to integrate they must extend our development api and thats all. $)

**Comment by fiote** [comment]
@zckrs Well I agree. But unless someone create a curse.com-like for tree of savior, we must stay around here, I guess =\

Also @Excrulon, I'm up for a one-for-all core library and style, and I don't mind changing my addons to fit it. I'm already seeing problems if multiple addons overwriting the same _G call, and that's going to get messier as time goes by. Wanna talk about it?

**Comment by zckrs** [comment]
Awesome installer could be a [Electron](http://electron.atom.io/) application

**Comment by Excrulon** [comment]
Yes we have a hook system in place already  just gotta get people to use it.

**Comment by Fornori** [comment]
So Maybe connect via discord or telegram create some group and get it? You can developer API, because I not strong in lua develpopment, but I can create GUI for install and manager addon.

**Comment by Excrulon** [comment]
I have a tos discord addon community, may make it public later.

**Comment by fiote** [comment]
@Excrulon If someone ever came up with a site/software to make addons available (like curse.com for wow addons), would you put your releases there? What do you think about it?

**Comment by Fornori** [comment]
Maybe you can send private invite?

**Comment by cyrilpangilinan** [comment]
@Excrulon Hit me up on the Discord community too

**Comment by fiote** [comment]
Well I never used discord but I just created an account there just for this, lol. My username there is fiote too. Please invite me/add me/whatever it is lol.

**Comment by cyrilpangilinan** [comment]
If you're familiar with Ventrilo/Raidcall/Teamspeak and the like, it's similar. Discord's just got better features I suppose.

**Comment by Excrulon** [comment]
Nah, discord is better than all of those in every way. I've had a tos addon
discord with me and a few others since November. I'll set it up for more
people when I'm not stuck at work.

**Comment by mc-crafty** [comment]
@Excrulon if you could also send an invite to X_I13 #9504 (me) that would awesome

**Comment by fiote** [comment]
@Excrulon fiote #3304 o/

**Comment by Excrulon** [comment]
Not too interested in that. I started working on an addon manager over four months ago but never finished because I thought it'd just be me making addons and I shifted my priorities on just making more addons nonstop. Now I think I'll pick it back up again and try to finish it up.

https://github.com/Excrulon/Tree-of-Savior-Mod-Manager

I have no desire to have things hosted on some random website and not be in control of my stuff. My plan is to have people create their addons and have it in their own github. Then, they'll have a branch/tag for each stable release. When they're ready to submit it, they'll create a pull request to [Tree of Savior Addon Community Addons](https://github.com/Tree-of-Savior-Addon-Community/Addons). This pull request will simply contain a json file or similar that defines release branch url to the author's github. The author's github will have a json file in the root of each addon that describes name/author/description/version/etc.

The addon manager app will read this list and allow you to check/uncheck which addons you want to download. I have downloads and progress bars working, just have to make it pull from github instead which should be super easy.

This way, everything is decentralized and everyone is in control of their own addons and they can choose when to release them. As long as people comply to using our hook system so that there are no conflicts and there's nothing malignant, they'll be pulled down.

I'll probably have an ipf or a flat folder structure that contains the hook library to use. I want to make it support both loading from an ipf and also from a folder structure like my current addon loader is doing. You don't gain much from packing addons inside of an ipf except that it's a little cleaner to distribute, being able to have your on init called automatically, and being able to register messages. With an addon manager, this doesn't even matter. It's also a bit more of a pain in development to use your own ipf. 

Anything requiring a custom ui will have to use a packed ipf because there is no way to do it in lua code (create frame from xml seems to be internal/debug use only and doesn't work). What I may consider doing is having a generic empty frame that people can create a copy of and modify it programmatically through lua. Will have to test the feasibility of this.

The only thing I've been trying to work out is dependency management. It'll end up being a nightmare if different addons are using a different version of someone's library. It's not really an easy problem to solve since most library functions will be in global. People will just have to keep their addons up to date if there's a need for breaking changes to an api and people making apis will just have to make sure to make no breaking changes and mark older things as deprecated.

**Comment by mc-crafty** [comment]
Big fan of that idea. It would help sort out duplicate hooking too. For instance, right now I know of 4 different addons hooking into running commands from in game chat. It gets messy really quick.

I'm willing to help out anyway I can.

**Comment by Excrulon** [comment]
Yes I've ran into hooking conflicts in my own addons alone, haha. And I think it's funny how every addon I see has copied my very naive/bad hooking method, haha.

Seen 3 or 4 slash command implementations as well. Just gonna have one standard one

**Comment by fiote** [comment]
Well well I'm here thinking about sticks and stones and @Excrulon comes up with a full laser blaster. I'll keep working on my addons then and will make any adjustments necessary when you addon manager come to life =]

About the hooking methods, my cwAPI.events.on actually let you hook some action to happen before the original event, after it, or instead of it. ^^

About slash commands, well yeah I did mine as well, lol. Would love to have some core API somewhere out there.

**Comment by TehSeph** [comment]
I'm a big fan of @fiote's api methods for hooking, commands, etc. and the auto-loading of his addonloader (which is compatible with your addons as well). Would love to see these things in the "standardized" format you're planning out. :smiley:

**Comment by Excrulon** [comment]
Yeah I'll look at everything and take a combination of all the best stuff. The first hook utility from back around November was written by SecurityRisk. This one is probably the most robust and we'll rounded but I'll have to test it more thoroughly. You can see that here.

https://github.com/messer00/TOSdev-API/blob/master/core/Utils.lua

There's also the start to a library that also has hooking that I might use that was written by someone I've been researching/collaborating with occasionally. https://github.com/Tree-of-Savior-Addon-Community/tos-plugins

I'll look at @fiote one when I get a chance and we'll decide as a group and improve on that one.

**Comment by fiote** [comment]
I just checked the TOSdev-API hook and yeah, it's better than mine since that one can hook multiple times to the same event (and even priorize them, lol). 

@Excrulon, do you want to make messer00 api the 'main' core? I'm not making you the leader on this lol, but since i'm good with anything, whatever you choose its good for me ^^

**Comment by Excrulon** [comment]
I'll be taking bits and pieces from multiple projects for the core. That
messer00 project has been dead for months and we never really did too much
more on it. I have some other code to include in a core library as well.

And yeah I mean I plan to take the lead on all of this... I already have
been and I did start this whole scene (not to sound too full of myself).

**Comment by fiote** [comment]
Well yes you did lol. I only started making addons because you addon showed up (I didnt even think they existed before that). ALL HAIL OUR ADDON OVERLORD \o/

**Comment by Excrulon** [comment]
Regardless, I still appreciate help from others. Not enough time in the
world to do all of it myself. I think by Wednesday night I could have the
basics of the addon manager downloading stuff. And then we'll go from there.

**Comment by cyrilpangilinan** [comment]
I agree that it would be nice to have a coding convention as well as some documentation. I have to admit I have only a little bit of knowledge about Lua and I guess this is my chance to learn.

**Comment by mc-crafty** [comment]
Yeah, a standard would be great. The reason I keeps using hooks as they are in the repos I fork is to try and keep some consistency; if only on a per repo basis. 
Also I agree, this is a chance to learn (or brush up on) lua. Last time I used it for anything was making an AI for my homun back on RO...

**Comment by Excrulon** [comment]
Decent progress made tonight. Still going to be at least a few more nights of work but the core functionality is almost done.

![Progress](http://i.imgur.com/31ztO6B.png)

Pulling down addons from here.

https://raw.githubusercontent.com/Tree-of-Savior-Addon-Community/Addons/master/addons.json

Should scale fine unless there ends up being like 1000+ addons, but I highly doubt there will be. If that happens, I'll restructure how things are stored. I like how simple this is.

**Comment by gonkyouka** [comment]
Wow that looks promising..

**Comment by fiote** [comment]
Material design! Sweet lol

**Comment by Excrulon** [comment]
yeah just a placeholder. I'll have to make a unique icon for it.

**Comment by TehSeph** [comment]
![Talt](http://www.tosbase.com/content/img/icons/items/30_item_ore_talt.png)

**Comment by Excrulon** [comment]
Thanks! I need 25,000 more of those for my guild!
