### ISSUE TITLE
Monster HP not refreshing

### ISSUE THREAD

**Issue by alexcoliveira1** [Excrulon/Tree-of-Savior-Lua-Mods#87]
Hey guys, I'm experiencing a problem with monster HP. When I atk them their life isn't refreshing, so thing like this image happens all the time.

![screenshot_20160507_00003](https://cloud.githubusercontent.com/assets/2866548/15092162/f58b5e86-142f-11e6-9b6c-f071a0b877f2.jpg)

Looks like that when using skills some times it works, but never with auto atks.

**Comment by zckrs** [comment]
I have seen same bug

**Comment by Hereticide** [comment]
I noticed this too and came here to comment.

The issue seems to be tied to the HP number not decreasing while the enemy is targeted. Releasing the target and then re-targeting the enemy forces the correct numerical update. If you are "Target Locked" on the enemy the number will never decrease but the bar will.
